name: Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - uses: actions/checkout@v3

    - name: Test
      run: go test ./...
